import { Open_Sans } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/shared/Header/Header";

const openSans = Open_Sans({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Provestor User",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} bg-[#F7F4F2]`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
